\c forum_db

DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS users CASCADE; 
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL,
location VARCHAR	
);


CREATE TABLE posts(
	id SERIAL PRIMARY KEY,
	topic VARCHAR NOT NULL,
	votes INTEGER DEFAULT 0
);

CREATE TABLE comments (
	id SERIAL PRIMARY KEY,
	comment VARCHAR NOT NULL,
	post_id INTEGER REFERENCES posts (id)
);